# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='rtpy',
    version='1.4.9',
    description='Python wrapper for the JFrog Artifactory REST API.',
    python_requires='!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<4.0,>=2.7',
    project_urls={"homepage": "https://github.com/Orange-OpenSource/rtpy"},
    author='Guillaume Renault',
    author_email='me@grenault.org',
    license='Apache-2.0',
    keywords='artifactory rest api wrapper',
    packages=['rtpy'],
    package_dir={"": "."},
    package_data={},
    install_requires=['requests==2.*,>=2.18.4'],
    extras_require={
        "dev": [
            "coverage==4.*,>=4.5.0", "poetry-setup==0.*,>=0.3.0",
            "pytest==3.*,>=3.6.0", "setuptools==40.*,>=40.0.0",
            "sphinx==1.*,>=1.8.2", "sphinx-rtd-theme==0.*,>=0.4.0",
            "sphinxcontrib-napoleon==0.*,>=0.7.0", "tox==3.*,>=3.2.0",
            "tox-pyenv==1.*,>=1.1.0"
        ]
    },
)
